### ISSUE TITLE
No such file or directory: rules_nasm.bzl in user project

### ISSUE THREAD

**Issue by dzenanz** [google/tensorstore#64]
I am trying to update to latest version of tensorstore, going from b8949f2157d09c4e1235fbc4af2852f05e3b4759 to af7dbb9c93f6a06ebf72a1a583718f5894f98262. I now get an error at configure time (log tail below). I assume that changes over the last week or two have introduced this. My build specification is [here](https://github.com/dzenanz/ITKIOOMEZarrNGFF/blob/tensorstore/src/CMakeLists.txt).

```log
Loading C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/aom-src/BUILD.bazel
Using bzl library: @com_google_tensorstore//:rules_nasm.bzl at C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/tensorstore-src/rules_nasm.bzl
Loading C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/tensorstore-src/rules_nasm.bzl

Traceback (most recent call last):

  File "C:\Dev\ITKIOOMEZarrNGFF-vs19\_deps\tensorstore-src\tools\cmake\bazel_to_cmake.py", line 41, in <module>

    sys.exit(bazel_to_cmake.main.main())

  File "C:\Dev\ITKIOOMEZarrNGFF-vs19\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\main.py", line 133, in main

    context.process_build_file(build_file)

  File "C:\Dev\ITKIOOMEZarrNGFF-vs19\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 457, in process_build_file

    self.process_build_content(build_file_path, self._load(build_file_path))

  File "C:\Dev\ITKIOOMEZarrNGFF-vs19\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 471, in process_build_content

    exec(compile(content, build_file_path, "exec"), scope)  # pylint: disable=exec-used

  File "C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/aom-src/BUILD.bazel", line 6, in <module>

    load("@com_google_tensorstore//:rules_nasm.bzl", "nasm_library")

  File "C:\Dev\ITKIOOMEZarrNGFF-vs19\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 593, in bazel_load

    library = self._context.get_library(library_target)

  File "C:\Dev\ITKIOOMEZarrNGFF-vs19\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 433, in get_library

    content = self._load(library_path)

  File "C:\Dev\ITKIOOMEZarrNGFF-vs19\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 451, in _load

    return pathlib.Path(path).read_text(encoding="utf-8")

  File "C:\Program Files\Python39\lib\pathlib.py", line 1266, in read_text

    with self.open(mode='r', encoding=encoding, errors=errors) as f:

  File "C:\Program Files\Python39\lib\pathlib.py", line 1252, in open

    return io.open(self, mode, buffering, encoding, errors, newline,

  File "C:\Program Files\Python39\lib\pathlib.py", line 1120, in _opener

    return self._accessor.open(self, flags, mode)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Dev\\ITKIOOMEZarrNGFF-vs19\\_deps\\tensorstore-src\\rules_nasm.bzl'

CMake Error at C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/aom-src/CMakeLists.txt:26 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"



Configuring incomplete, errors occurred!
```
The following file exists: `C:\Dev\ITKIOOMEZarrNGFF-vs19\_deps\tensorstore-src\bazel\rules_nasm.bzl`.

**Comment by dzenanz** [comment]
I did reuse `_deps` directory. Can I only blow away part of it, or do I have to remove the whole thing?

**Comment by jbms** [comment]
You can just delete individual directories --- you should delete both the -src and -build directory together, though.

**Comment by dzenanz** [comment]
Removing `tensorstore-*` from `_deps` didn't do the trick. I will just remove whole `_deps`, and if that doesn't help, do a completely clean build.

**Comment by dzenanz** [comment]
Removing `_deps` got me past this error. Thank you Jeremy.
