### ISSUE TITLE
Python 3.7 no longer supported?

### ISSUE THREAD

**Issue by dzenanz** [google/tensorstore#68]
With the latest version of the library (efca7ed88fcdc6e2a64bdb12626cdaeb92b92ecb), I am running into a CMake configure error (log excerpt below) with Python 3.7. This does not happen with Python 3.8. Should [documentation](https://google.github.io/tensorstore/installation.html#cmake-build-dependencies) be updated to state that Python 3.8 is the minimum?

```log
...
Using library: @com_google_tensorstore//third_party:nasm/workspace.bzl at /work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/third_party/nasm/workspace.bzl
Loading /work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/third_party/nasm/workspace.bzl
Using library: @com_google_tensorstore//third_party:net_sourceforge_half/workspace.bzl at /work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/third_party/net_sourceforge_half/workspace.bzl
Traceback (most recent call last):
  File "/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/tools/cmake/bazel_to_cmake.py", line 41, in <module>
    sys.exit(bazel_to_cmake.main.main())
  File "/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/tools/cmake/bazel_to_cmake/main.py", line 138, in main
    state.process_build_file(build_file)
  File "/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/tools/cmake/bazel_to_cmake/evaluation.py", line 481, in process_build_file
    self.process_build_content(build_file_path, self._load(build_file_path))
  File "/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/tools/cmake/bazel_to_cmake/evaluation.py", line 502, in process_build_content
    exec(compile(content, build_file_path, "exec"), scope)  # pylint: disable=exec-used
  File "/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/BUILD.bazel", line 47, in <module>
    ":arm64",
  File "/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/tools/cmake/bazel_to_cmake/bzl_library/bazel_skylib.py", line 80, in config_setting_group
    analyze_by_default=True)
  File "/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/tools/cmake/bazel_to_cmake/evaluation.py", line 637, in add_rule
    self._state.add_rule(rule_id, impl, outs, **kwargs)
  File "/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/tools/cmake/bazel_to_cmake/evaluation.py", line 212, in add_rule
    for out_id in r.outs:
  File "/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/tensorstore-src/tools/cmake/bazel_to_cmake/evaluation.py", line 120, in __getitem__
    return getattr(self, item, None)
TypeError: getattr(): attribute name must be string
```

**Comment by laramiel** [comment]
I should have a fix for that with my next commit.

**Comment by laramiel** [comment]
I think that this should be fixed by:
https://github.com/google/tensorstore/commit/5f189a84e7a54b8964d8cf5bf9a4dd3ecfd59450

**Comment by dzenanz** [comment]
I think this fixed it.
